server:
  port: 9090
spring:  datasource:    url: jdbc:mysql://localhost:3306/hibernate?serverTimezone=UTC&useSSL=false
    username: root
    password:     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    